apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ .Values.fqdn | replace "." "-" }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.fqdn | replace "." "-" }}
  sessionAffinity: None
  type: ClusterIP
